
  server:
    context-path: /cmfz
    port: 8081
    jsp-servlet:
      init-parameters:
        development: true
  spring:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3306/yanzhixiang
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 111111
    mvc:
      view:
        prefix: /
        suffix: .jsp
    http:
      multipart:
        max-file-size: 10Mb
        max-request-size: 100Mb
      encoding:
        charset: utf-8
        force: true
  mybatis:
    type-aliases-package: com.baizhi.cmfz.entity
    mapper-locations: com/baizhi/cmfz/dao/*Dao.xml
